Repository Team8-Project/back, pull requests merged in 2022-01, with the labels that each got.

#305 [Dict] 좋아요, 좋아요 취소 기능 성능 개선
  src/main/java/com/teamproj/backend/dto/dict/DictSearchResultResponseDto.java
  src/main/java/com/teamproj/backend/service/DictService.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: enhancement

#310 배포
  src/main/java/com/teamproj/backend/dto/dict/DictSearchResultResponseDto.java
  src/main/java/com/teamproj/backend/service/DictService.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: deploy

#311 [Board] 조회 성능 개선
  src/main/java/com/teamproj/backend/Repository/board/BoardRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
  src/main/java/com/teamproj/backend/exception/RestApiExceptionHandler.java
  src/main/java/com/teamproj/backend/service/BoardService.java
  src/main/java/com/teamproj/backend/service/CommentService.java
  src/main/java/com/teamproj/backend/service/DictService.java
  src/main/java/com/teamproj/backend/util/MemegleServiceStaticMethods.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: enhancement

#315 [newFunc] 추가 기능 껍데기 추가
  src/main/java/com/teamproj/backend/Repository/dict/DictCuriousRepository.java
  src/main/java/com/teamproj/backend/controller/DictCuriousController.java
  src/main/java/com/teamproj/backend/controller/RankController.java
  src/main/java/com/teamproj/backend/dto/dict/DictNameCheckResponseDtoNeo.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostRequestDto.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostResponseDto.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousResponseDto.java
  src/main/java/com/teamproj/backend/dto/rank/RankDictAllTimeResponseDto.java
  src/main/java/com/teamproj/backend/dto/rank/RankResponseDto.java
  src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
  src/main/java/com/teamproj/backend/model/admin/BanList.java
  src/main/java/com/teamproj/backend/model/dict/DictCurious.java
  src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
  src/main/java/com/teamproj/backend/service/AdminService.java
  src/main/java/com/teamproj/backend/service/BoardService.java
  src/main/java/com/teamproj/backend/service/DictCuriousService.java
  src/main/java/com/teamproj/backend/service/DictService.java
  src/main/java/com/teamproj/backend/service/RankService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
Labels: TODO

#317 [Board] 게시글 조회시 삭제된 댓글 개수 계산되는 문제
  src/main/java/com/teamproj/backend/service/BoardService.java
Labels: bug

#318 [Stat] 방문자 누적되지 않는 문제
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: bug

#319 배포
  src/main/java/com/teamproj/backend/Repository/dict/DictCuriousRepository.java
  src/main/java/com/teamproj/backend/controller/DictCuriousController.java
  src/main/java/com/teamproj/backend/controller/RankController.java
  src/main/java/com/teamproj/backend/dto/dict/DictNameCheckResponseDtoNeo.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostRequestDto.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousPostResponseDto.java
  src/main/java/com/teamproj/backend/dto/dictCurious/DictCuriousResponseDto.java
  src/main/java/com/teamproj/backend/dto/rank/RankDictAllTimeResponseDto.java
  src/main/java/com/teamproj/backend/dto/rank/RankResponseDto.java
  src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
  src/main/java/com/teamproj/backend/model/admin/BanList.java
  src/main/java/com/teamproj/backend/model/dict/DictCurious.java
  src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
  src/main/java/com/teamproj/backend/service/AdminService.java
  src/main/java/com/teamproj/backend/service/BoardService.java
  src/main/java/com/teamproj/backend/service/DictCuriousService.java
  src/main/java/com/teamproj/backend/service/DictService.java
  src/main/java/com/teamproj/backend/service/RankService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
Labels: deploy

#325 [newFunc] WebSecurity 수정
  src/main/java/com/teamproj/backend/controller/DictQuestionController.java
  src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
Labels: enhancement

#327 [DictQuestion] 기능 추가 중
  src/main/java/com/teamproj/backend/Repository/dict/QuestionSelectRepository.java
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/controller/DictCuriousController.java
  src/main/java/com/teamproj/backend/controller/DictQuestionCommentController.java
  src/main/java/com/teamproj/backend/controller/DictQuestionController.java
  src/main/java/com/teamproj/backend/exception/RestApiExceptionHandler.java
  src/main/java/com/teamproj/backend/model/dict/question/DictQuestionComment.java
  src/main/java/com/teamproj/backend/model/dict/question/QuestionCommentLike.java
  src/main/java/com/teamproj/backend/service/MainService.java
  src/main/java/com/teamproj/backend/service/RankService.java
  src/main/java/com/teamproj/backend/service/admin/AdminService.java
  src/main/java/com/teamproj/backend/service/admin/AlarmService.java
  src/main/java/com/teamproj/backend/service/dict/DictCuriousService.java
  src/main/java/com/teamproj/backend/service/dict/DictHistoryService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
  src/test/java/com/teamproj/backend/service/DictHistoryServiceTest.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: TODO

#328 [Alarm] 알람 기능
  src/main/java/com/teamproj/backend/Repository/alarm/AlarmRepository.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: TODO

#329 [newFunc] 새로 만들어진 기능 반영
  src/main/java/com/teamproj/backend/Repository/dict/QuestionCommentLikeRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/QuestionSelectRepository.java
  src/main/java/com/teamproj/backend/controller/DictQuestionCommentController.java
  src/main/java/com/teamproj/backend/dto/dict/question/comment/DictQuestionCommentResponseDto.java
  src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
  src/main/java/com/teamproj/backend/model/dict/question/QuestionCommentLike.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/util/MemegleServiceStaticMethods.java
Labels: enhancement, TODO

#330 [Dict] 사전 검색 containing으로 복구
  src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: enhancement

#331 [Dict] 검색 시 글자 없으면 빈 배열 반환하도록 설정
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: enhancement

#332 [DictQuestion] 사용자 이름 비정상출력 문제 해결
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: bug

#335 [DictQuestion] 비회원 상세조회 불가능한 버그
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: bug

#336 배포
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: deploy

#339 [Dict] 사전 페이지 기능 추가
  src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/controller/StatController.java
  src/main/java/com/teamproj/backend/dto/statistics/StatDictPostByDayDto.java
  src/main/java/com/teamproj/backend/dto/statistics/StatDictQuestionListDto.java
  src/main/java/com/teamproj/backend/dto/statistics/StatDictResponseDto.java
  src/main/java/com/teamproj/backend/security/WebSecurityConfig.java
  src/main/java/com/teamproj/backend/service/RankService.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/RedisKey.java
Labels: enhancement, TODO

#341 [Dict] 통계 기능 Redis Cache 만료기한 추가
  src/main/java/com/teamproj/backend/service/RedisService.java
Labels: enhancement

#344 [DIct] Redis 수정
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: enhancement

#345 배포
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#346 [Dict] 다시 배포
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: enhancement

#347 배포
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#348 [Dict] Redis 제외 후 배포
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: enhancement

#349 배포
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#350 [DictQuestion] 좋아요 취소되지 않는 현상 수정
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: bug

#351 [DictQuestion] 나도궁금해요 해결
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: bug

#352 배포
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: deploy

#353 [Dict] 사전 통계 캐싱 배포 테스트
  src/main/java/com/teamproj/backend/dto/statistics/StatDictResponseDto.java
  src/main/java/com/teamproj/backend/dto/user/userInfo/UserInfoResponseDto.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/MainService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/UserService.java
Labels: enhancement

#354 배포
  src/main/java/com/teamproj/backend/dto/statistics/StatDictResponseDto.java
  src/main/java/com/teamproj/backend/dto/user/userInfo/UserInfoResponseDto.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/MainService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/UserService.java
Labels: deploy

#356 [Dict] 통계 데이터 Redis 캐싱 완료
  src/main/java/com/teamproj/backend/service/RedisService.java
Labels: enhancement

#357 [Dict] 통계 데이터 요일 일주일 모두 표시되게 변경
  src/main/java/com/teamproj/backend/Repository/quiz/QuizBankRepository.java
  src/main/java/com/teamproj/backend/dto/statistics/StatDictPostByDayDto.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: enhancement

#358 배포
  src/main/java/com/teamproj/backend/Repository/quiz/QuizBankRepository.java
  src/main/java/com/teamproj/backend/dto/statistics/StatDictPostByDayDto.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#359 [Dict] 스크랩 기능
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/dto/dict/mymeme/DictMyMemeResponseDto.java
  src/main/java/com/teamproj/backend/model/dict/DictLike.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: TODO

#362 [Naver] 소셜로그인 ID 변경
  src/main/java/com/teamproj/backend/Repository/UserRepository.java
  src/main/java/com/teamproj/backend/dto/user/social/naver/NaverUserInfoDto.java
  src/main/java/com/teamproj/backend/exception/RestApiExceptionHandler.java
  src/main/java/com/teamproj/backend/model/User.java
  src/main/java/com/teamproj/backend/service/NaverUserService.java
Labels: bug

#363 [Common] CORS 정책 변경
  src/main/java/com/teamproj/backend/config/MvcConfig.java
Labels: enhancement

#364 배포
  src/main/java/com/teamproj/backend/config/MvcConfig.java
Labels: deploy

#365 [DictQuestion] 비회원 상세조회 안되는 현상
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
Labels: bug

#366 배포
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
Labels: deploy

#367 [Dict] 유튜브 관련동영상 추가 외
  build.gradle
  src/main/java/com/teamproj/backend/Repository/dict/DictYoutubeUrlRepository.java
  src/main/java/com/teamproj/backend/config/MvcConfig.java
  src/main/java/com/teamproj/backend/dto/dict/DictDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/dict/question/detail/DictQuestionDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/youtube/YoutubeSearchResultDto.java
  src/main/java/com/teamproj/backend/model/dict/Dict.java
  src/main/java/com/teamproj/backend/model/dict/DictHistory.java
  src/main/java/com/teamproj/backend/model/dict/DictYoutubeUrl.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/YoutubeService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: bug, enhancement, TODO

#368 배포
  build.gradle
  src/main/java/com/teamproj/backend/Repository/dict/DictYoutubeUrlRepository.java
  src/main/java/com/teamproj/backend/config/MvcConfig.java
  src/main/java/com/teamproj/backend/dto/dict/DictDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/dict/question/detail/DictQuestionDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/youtube/YoutubeSearchResultDto.java
  src/main/java/com/teamproj/backend/model/dict/Dict.java
  src/main/java/com/teamproj/backend/model/dict/DictHistory.java
  src/main/java/com/teamproj/backend/model/dict/DictYoutubeUrl.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/YoutubeService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: deploy

#369 [Dict] 관련동영상에 썸네일 컬럼 추가
  src/main/java/com/teamproj/backend/model/dict/DictYoutubeUrl.java
  src/main/java/com/teamproj/backend/service/YoutubeService.java
Labels: enhancement

#370 배포
  src/main/java/com/teamproj/backend/model/dict/DictYoutubeUrl.java
  src/main/java/com/teamproj/backend/service/YoutubeService.java
Labels: deploy

#371 [Dict] 주석 작업 및 성능 개선
  src/main/java/com/teamproj/backend/dto/dict/DictDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/dict/mymeme/DictMyMemeResponseDto.java
  src/main/java/com/teamproj/backend/dto/youtube/DictRelatedYoutubeDto.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: enhancement

#376 [Alarm] 알림 자신의 알람이 처리가 되지 않는 현상
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: bug

#377 배포
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: deploy

#379 배포
  src/main/java/com/teamproj/backend/config/MvcConfig.java
Labels: deploy

#380 [Dict] 통계 부분 정렬 기준 추가
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: enhancement

#381 배포
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#382 [Alarm] 알람 전체 읽음 처리 기능 추가
  src/main/java/com/teamproj/backend/Repository/alarm/AlarmRepository.java
  src/main/java/com/teamproj/backend/controller/AlarmController.java
  src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/NaverUserService.java
Labels: enhancement, TODO

#383 배포
  src/main/java/com/teamproj/backend/Repository/alarm/AlarmRepository.java
  src/main/java/com/teamproj/backend/controller/AlarmController.java
  src/main/java/com/teamproj/backend/exception/ExceptionMessages.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/NaverUserService.java
Labels: deploy

#384 [Dict] 질문 페이지 목록조회 댓글 개수 정상 출력되지 않는 현상
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: bug

#385 배포
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
Labels: deploy

#388 [Dict] 사전 및 사전질문 상세보기, 목록보기 성능 개선
  src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/DictViewersRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/DictYoutubeUrlRepository.java
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/model/dict/question/DictQuestion.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
Labels: enhancement

#389 배포
  src/main/java/com/teamproj/backend/Repository/dict/DictRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/DictViewersRepository.java
  src/main/java/com/teamproj/backend/Repository/dict/DictYoutubeUrlRepository.java
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/model/dict/question/DictQuestion.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionCommentService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
Labels: deploy

#394 [Dict] 목록에서 나도궁금해요 true로 나오는 버그 수정
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: bug

#393 feat/kakao login responseDto수정
  src/main/java/com/teamproj/backend/controller/UserController.java
  src/main/java/com/teamproj/backend/dto/user/social/kakao/KakaoUserResponseDto.java
  src/main/java/com/teamproj/backend/service/KakaoUserService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
Labels: deploy

#395 [Common] https 사이트 CORS 개방
  src/main/java/com/teamproj/backend/config/MvcConfig.java
Labels: enhancement

#396 배포
  src/main/java/com/teamproj/backend/config/MvcConfig.java
Labels: deploy

#397 [Alarm] 알람에 레디스 캐싱 적용 및 쿼리 조회 횟수 감소
  src/main/java/com/teamproj/backend/model/User.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/util/RedisKey.java
Labels: enhancement

#398 배포
  src/main/java/com/teamproj/backend/model/User.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/util/RedisKey.java
Labels: deploy

#399 [Alarm] 알람 읽음처리 redis에 반영
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: enhancement

#400 배포
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: deploy

#403 [Alarm] 버그 수정 후 배포
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: bug

#404 배포
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: deploy

#405 [Dict] 통계 삭제한 게시글도 나오는 문제 해결
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: bug

#406 배포
  src/main/java/com/teamproj/backend/service/StatService.java
Labels: deploy

#415 [Dict] 유튜브 썸네일 더 큰 사이즈로 가져오도록 변경
  src/main/java/com/teamproj/backend/service/YoutubeService.java
Labels: enhancement

#416 배포
  src/main/java/com/teamproj/backend/service/YoutubeService.java
Labels: deploy

#417 [Board] 짤방게시판 성능 개선
  src/main/java/com/teamproj/backend/Repository/board/BoardViewersRepository.java
  src/main/java/com/teamproj/backend/config/MvcConfig.java
  src/main/java/com/teamproj/backend/dto/board/BoardDetail/BoardDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/board/BoardResponseDto.java
  src/main/java/com/teamproj/backend/model/board/BoardCategory.java
  src/main/java/com/teamproj/backend/service/BoardService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: enhancement

#418 배포
  src/main/java/com/teamproj/backend/Repository/board/BoardViewersRepository.java
  src/main/java/com/teamproj/backend/config/MvcConfig.java
  src/main/java/com/teamproj/backend/dto/board/BoardDetail/BoardDetailResponseDto.java
  src/main/java/com/teamproj/backend/dto/board/BoardResponseDto.java
  src/main/java/com/teamproj/backend/model/board/BoardCategory.java
  src/main/java/com/teamproj/backend/service/BoardService.java
  src/main/java/com/teamproj/backend/service/StatService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
Labels: deploy

#419 [Board] 비로그인 유저 짤 상세정보 볼 수 없는 현상
  src/main/java/com/teamproj/backend/service/BoardService.java
Labels: bug

#420 배포
  src/main/java/com/teamproj/backend/service/BoardService.java
Labels: deploy

#421 [Test] 테스트코드 작성
  build.gradle
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/controller/DictCuriousController.java
  src/main/java/com/teamproj/backend/dto/user/userInfo/UserNicknameModifyRequestDto.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/admin/AdminService.java
  src/main/java/com/teamproj/backend/service/dict/DictCuriousService.java
  src/main/java/com/teamproj/backend/service/dict/DictHistoryService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/Scheduler.java
  src/test/java/com/teamproj/backend/config/S3MockConfig.java
  src/test/java/com/teamproj/backend/dto/LoginRequestDto.java
  src/test/java/com/teamproj/backend/kakaoLoginTest/KakaoLoginTest.java
  src/test/java/com/teamproj/backend/security/MockSpringSecurityFilter.java
  src/test/java/com/teamproj/backend/service/DictHistoryServiceTest.java
  src/test/java/com/teamproj/backend/service/DictServiceTest.java
  src/test/java/com/teamproj/backend/service/MyPageServiceTest.java
  src/test/java/com/teamproj/backend/service/UserServiceTest.java
  src/test/java/com/teamproj/backend/service/dict/DictHistoryServiceTest.java
  src/test/java/com/teamproj/backend/service/dict/DictQuestionCommentServiceTest.java
  src/test/java/com/teamproj/backend/service/dict/DictQuestionServiceTest.java
  src/test/java/com/teamproj/backend/service/dict/DictServiceTest.java
Labels: TODO

#422 [Dict] 오늘의 밈 받아오기 코드 변경 외
  src/main/java/com/teamproj/backend/dto/alarm/AlarmResponseDto.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/dict/DictQuestionService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/MemegleServiceStaticMethods.java
Labels: enhancement

#425 [Test] 테스트코드 작성
  build.gradle
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/controller/QuizController.java
  src/main/java/com/teamproj/backend/model/dict/DictCurious.java
  src/main/java/com/teamproj/backend/model/quiz/Quiz.java
  src/main/java/com/teamproj/backend/service/NaverUserService.java
  src/main/java/com/teamproj/backend/service/QuizService.java
  src/main/java/com/teamproj/backend/service/RankService.java
  src/main/java/com/teamproj/backend/service/YoutubeService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/test/java/com/teamproj/backend/controller/DictControllerTest.java
  src/test/java/com/teamproj/backend/controller/UserControllerTest.java
  src/test/java/com/teamproj/backend/service/BoardServiceTest.java
  src/test/java/com/teamproj/backend/service/QuizServiceTest.java
  src/test/java/com/teamproj/backend/service/YoutubeServiceTest.java
  src/test/java/com/teamproj/backend/service/dict/DictServiceTest.java
  src/test/java/com/teamproj/backend/service/stat/RankServiceTest.java
  src/test/java/com/teamproj/backend/service/user/NaverUserServiceTest.java
  src/test/java/com/teamproj/backend/service/user/UserServiceTest.java
Labels: TODO

#429 [Dict] 동시에 수정 못 하도록 하는 기능 외
  build.gradle
  src/main/java/com/teamproj/backend/Repository/dict/DictCuriousRepository.java
  src/main/java/com/teamproj/backend/controller/DictController.java
  src/main/java/com/teamproj/backend/service/AlarmService.java
  src/main/java/com/teamproj/backend/service/RedisService.java
  src/main/java/com/teamproj/backend/service/dict/DictService.java
  src/main/java/com/teamproj/backend/util/RedisKey.java
Labels: TODO

#431 [Test] 사전 테스트 BeforeEach 수정
  src/test/java/com/teamproj/backend/service/dict/DictServiceTest.java
Labels: enhancement

#436 [Alarm] 알람 꺼지지 않는 버그 수정
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: bug

#435 배포
  README.md
  src/main/java/com/teamproj/backend/service/AlarmService.java
Labels: deploy
